name: Run Python Script

on:
  workflow_dispatch:
    inputs:
      x_link:
        description: 'The X link to process'
        required: true
      category:
        description: 'The category for the X link'
        required: true

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib requests_html notion_client lxml_html_clean nest_asyncio

    - name: Run Python script
      env:
        SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
      run: |
        echo "X_LINK=${{ github.event.inputs.x_link }}" >> $GITHUB_ENV
        echo "CATEGORY=${{ github.event.inputs.category }}" >> $GITHUB_ENV
        python main_script.py
